"use client";
import { Printer as ActionPrinter, Search as ActionSearch, Tags as ActionTags, CheckCircle2 as ActionCheckCircle2, ArrowLeft as ActionArrowLeft } from "./icons";
import { useEffect, useState } from "react";
import { Search, ShoppingBag, Minus, Plus, CheckCircle2, ArrowLeft, Wallet } from "./icons";
import { api } from "@/lib/client";
import { fullName, money, type Order, type Product, type Student } from "@/lib/types";
import { Modal, Notice } from "./ui";
import { Receipt } from "./receipt";
import { useOrderingPeriod } from "@/lib/use-ordering-period";
import { termLabel, thaiDateTime } from "@/lib/terms";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faBagShopping, faCartShopping, faClockRotateLeft } from "@fortawesome/free-solid-svg-icons";

export function StudentOrdering({ history = false }: { history?: boolean }) {
  const { period, error: periodError, canOrder } = useOrderingPeriod();
  const [acknowledgeUnusedBudget, setAcknowledgeUnusedBudget] = useState(false);
  const [id, setId] = useState(""); const [student, setStudent] = useState<Student | null>(null);
  const [products, setProducts] = useState<Product[]>([]); const [cart, setCart] = useState<Record<number, number>>({});
  const [category, setCategory] = useState(""); const [search, setSearch] = useState("");
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const [order, setOrder] = useState<Order | null>(null); const [confirm, setConfirm] = useState(false); const [receipt, setReceipt] = useState(false);
  useEffect(() => {
    if (history && period && order && order.term_id !== period.term_id) { setOrder(null); setReceipt(false); }
  }, [history, period, order]);
  const periodChanged = !!student && !!period && student.term_id !== period.term_id;
  const orderingAllowed = canOrder && !periodChanged;
  const lines = products.filter(p => cart[p.product_id] > 0);
  const total = lines.reduce((sum, p) => sum + Math.round(p.price * 100) * cart[p.product_id], 0) / 100;
  const remaining = Math.round(((student?.budget || 0) - total) * 100) / 100;
  async function lookup(e: React.FormEvent) {
    e.preventDefault(); setError(""); setBusy(true); setStudent(null); setOrder(null); setCart({});
    try {
      if (history) { setOrder(await api<Order>("getStudentOrder", id, period?.term_id)); }
      else {
        const s = await api<Student>("getStudentById", id);
        if (s.has_ordered) { const saved = await api<Order>("getStudentOrder", id, s.term_id); setStudent(s); setOrder(saved); }
        else { const data = await api<Product[]>("getProducts"); setProducts(data); setStudent(s); }
      }
    } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  async function submit() {
    if (!student || busy || !orderingAllowed || remaining < 0 || (remaining > 0 && !acknowledgeUnusedBudget)) return;
    setBusy(true); setError("");
    try { const saved = await api<Order>("submitOrder", student.student_id, lines.map(p => ({ product_id: p.product_id, quantity: cart[p.product_id] })), acknowledgeUnusedBudget, student.term_id); setOrder(saved); setCart({}); setConfirm(false); }
    catch (e) { setError((e as Error).message); setConfirm(false); } finally { setBusy(false); }
  }
  const reset = () => { setStudent(null); setOrder(null); setCart({}); setError(""); setSearch(""); setCategory(""); };
  return <><div className="app-content"><div className="mb-7"><p className="mb-2 text-sm font-semibold text-sky-700">สำหรับนักเรียน</p><h1 className="flex items-center gap-3"><FontAwesomeIcon className="h-7 w-7 text-sky-700" icon={history ? faClockRotateLeft : faBagShopping} /><span>{history ? `ตรวจสอบรายการที่สั่ง${period ? ` · ${termLabel(period)}` : ""}` : "สั่งซื้ออุปกรณ์การเรียน"}</span></h1>{period && !history && <p className="mt-2 text-sm text-slate-500">{period.closes_at ? `ปิดรับวันที่ ${thaiDateTime(period.closes_at)} น.` : "ยังไม่กำหนดวันปิดรับ"}</p>}</div><Notice message={error || periodError} />{periodChanged && <Notice message="ภาคเรียนมีการเปลี่ยนแปลง กรุณากดเปลี่ยนนักเรียนแล้วค้นหาใหม่ก่อนสั่งซื้อ" />}
    {!student && !order && <section className="mx-auto mt-10 max-w-xl overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="bg-sky-700 px-7 py-8 text-white"><ShoppingBag size={32} className="mb-4" /><h2>{history ? "ค้นหาใบสั่งซื้อของคุณ" : "เริ่มต้นสั่งซื้ออุปกรณ์"}</h2><p className="mt-2 text-sm leading-6 text-sky-100">กรอกเลขประจำตัวนักเรียน 5 หลักเพื่อ{history ? "ตรวจสอบรายการที่สั่งไว้" : "ตรวจสอบข้อมูลและเลือกอุปกรณ์"}</p></div><form onSubmit={lookup} className="p-7"><label className="label" htmlFor="student-id">เลขประจำตัวนักเรียน</label><input id="student-id" className="field text-xl tracking-widest" inputMode="numeric" pattern="[0-9]{5}" maxLength={5} value={id} onChange={e => setId(e.target.value.replace(/\D/g, ""))} placeholder="เลขประจำตัว 5 หลัก" required autoComplete="off" /><button className="btn mt-5 w-full" disabled={busy || id.length !== 5 || (history && (!period || !!periodError))}><Search size={18} />{busy ? "กำลังค้นหา…" : "ค้นหาข้อมูล"}</button><p className="muted mt-5">หากไม่พบข้อมูล กรุณาติดต่อครูผู้รับผิดชอบ</p></form></section>}
    {order && <section className="panel mx-auto max-w-2xl"><CheckCircle2 className="mb-4 text-emerald-600" size={42} /><h2>{history || student?.has_ordered ? "นักเรียนสั่งซื้อเรียบร้อยแล้ว" : "บันทึกคำสั่งซื้อสำเร็จ"}</h2><p className="mt-4 font-semibold">{order.student_name}</p><p className="muted">{order.term_label}</p><p className="muted">ชั้น {order.grade}/{order.room} · เลขที่ {order.student_number ?? "—"} · เลขประจำตัว {order.student_id}</p><p className="my-5 text-3xl font-bold text-sky-700">{money(order.total_amount)} <span className="text-base font-normal">บาท</span></p><div className="flex flex-wrap gap-3"><button className="btn" onClick={() => setReceipt(true)}><ActionPrinter className="mr-1.5" />ดูรายการ / พิมพ์ใบสั่งซื้อ</button><button className="btn-secondary" onClick={reset}><ActionSearch className="mr-1.5" />ค้นหานักเรียนคนอื่น</button></div></section>}
    {student && !order && <><button className="btn-secondary mb-5" onClick={reset}><ArrowLeft size={16} />เปลี่ยนนักเรียน</button><div className="mb-6 flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-sky-200 bg-sky-50 p-5"><div><h2>{fullName(student)}</h2><p className="muted mt-1">เลขประจำตัว {student.student_id} · ชั้น {student.grade}/{student.room} · เลขที่ {student.student_number}</p></div><div className="flex items-center gap-3 text-sky-800"><Wallet /><div><p className="text-sm">งบประมาณของคุณ</p><p className="text-2xl font-bold">{money(student.budget)} บาท</p></div></div></div>
      <div className="grid items-start gap-6 xl:grid-cols-[1fr_320px]"><section><div className="mb-4"><label htmlFor="product-search" className="sr-only">ค้นหาอุปกรณ์</label><input id="product-search" className="field" placeholder="ค้นหาอุปกรณ์…" value={search} onChange={e => setSearch(e.target.value)} /></div><div className="mb-5 flex flex-wrap gap-2">{["", ...new Set(products.map(p => p.category))].map(c => <button key={c} aria-pressed={category === c} onClick={() => setCategory(c)} className={`rounded-full border px-4 py-2 text-sm ${category === c ? "border-sky-700 bg-sky-700 text-white" : "border-slate-200 bg-white text-slate-600"}`}><ActionTags className="mr-1.5" />{c || "ทั้งหมด"}</button>)}</div>
        <div className="grid gap-3 sm:grid-cols-2 2xl:grid-cols-3">{products.filter(p => (!category || p.category === category) && p.name.toLowerCase().includes(search.toLowerCase())).map(p => <article key={p.product_id} className={`flex flex-col rounded-xl border p-5 ${cart[p.product_id] ? "border-sky-500 bg-sky-50" : "border-slate-200 bg-white"}`}><p className="muted mb-2">{p.category}</p><h3 className="grow text-base leading-7">{p.name}</h3><p className="my-4 text-xl font-bold text-sky-700">{money(p.price)} <span className="text-sm font-normal text-slate-500">บาท</span></p><div className="flex items-center justify-between gap-3"><button type="button" className="btn-secondary px-3" aria-label={`ลดจำนวน ${p.name}`} disabled={!cart[p.product_id]} onClick={() => setCart(c => ({ ...c, [p.product_id]: Math.max(0, (c[p.product_id] || 0) - 1) }))}><Minus size={16} /></button><span aria-live="polite" className="font-semibold">{cart[p.product_id] || 0}</span><button className="btn-secondary px-3" aria-label={`เพิ่มจำนวน ${p.name}`} disabled={!orderingAllowed || Math.round(total * 100) + Math.round(p.price * 100) > Math.round(student.budget * 100) || (cart[p.product_id] || 0) >= 999} onClick={() => setCart(c => ({ ...c, [p.product_id]: (c[p.product_id] || 0) + 1 }))}><Plus size={16} /></button></div></article>)}</div>{!products.filter(p => (!category || p.category === category) && p.name.includes(search)).length && <p className="py-10 text-center text-slate-500">ไม่พบอุปกรณ์ที่ค้นหา</p>}
      </section><aside className="overflow-hidden rounded-2xl border border-slate-200 bg-white xl:sticky xl:top-6"><h2 className="flex items-center gap-3 bg-slate-900 p-5 text-lg text-white"><FontAwesomeIcon className="h-5 w-5" icon={faCartShopping} />รายการที่เลือก</h2><div className="p-5">{!lines.length ? <p className="muted py-6 text-center">เลือกอุปกรณ์จากรายการด้านซ้าย</p> : <div className="max-h-80 overflow-y-auto">{lines.map(p => <div key={p.product_id} className="flex gap-3 border-b border-slate-100 py-3 text-sm"><span className="flex-1">{p.name} <span className="text-slate-500">× {cart[p.product_id]}</span></span><strong>{money(p.price * cart[p.product_id])}</strong></div>)}</div>}<div className="mt-5 space-y-3"><div className="flex justify-between text-sm"><span>งบประมาณ</span><span>{money(student.budget)} บาท</span></div><div className="flex justify-between text-xl font-bold text-sky-800"><span>ยอดรวม</span><span>{money(total)} บาท</span></div><div className={`flex justify-between text-sm ${remaining < 0 ? "text-red-700" : "text-emerald-700"}`}><span>งบคงเหลือ</span><span>{money(remaining)} บาท</span></div></div><button className="btn mt-6 w-full" disabled={!orderingAllowed || !lines.length || remaining < 0 || busy} onClick={() => { setAcknowledgeUnusedBudget(false); setConfirm(true); }}><ActionCheckCircle2 className="mr-1.5" />ตรวจสอบและยืนยัน</button><p className="muted mt-3">สั่งซื้อได้ 1 ครั้งต่อคนต่อภาคเรียน ภายในงบที่ได้รับ</p></div></aside></div>
    </>}
    </div>{confirm && student && <Modal title="ยืนยันคำสั่งซื้อ" close={() => { if (!busy) setConfirm(false); }}><p className="muted mb-2">{period ? termLabel(period) : ""}</p>{!orderingAllowed && <Notice message={periodChanged ? "ภาคเรียนเปลี่ยนแล้ว กรุณาค้นหานักเรียนใหม่" : "ขณะนี้ไม่อยู่ในช่วงรับคำสั่งซื้อ กรุณาตรวจสอบกำหนดเวลาอีกครั้ง"} />}<p className="mb-4 font-semibold">{fullName(student)} · {student.grade}/{student.room} · เลขที่ {student.student_number}</p><div className="space-y-3">{lines.map(p => <div className="flex justify-between gap-4 text-sm" key={p.product_id}><span>{p.name} × {cart[p.product_id]}</span><strong>{money(p.price * cart[p.product_id])} บาท</strong></div>)}</div><p className="mt-5 border-t pt-5 text-xl font-bold">ยอดรวม {money(total)} บาท</p><p className="muted mt-3">หลังยืนยัน หากต้องการเปลี่ยนรายการ กรุณาติดต่อผู้ดูแลเพื่อยกเลิกคำสั่งซื้อก่อน</p>{remaining > 0 && <div className="mt-5 rounded-xl border border-amber-300 bg-amber-50 p-4 text-amber-950"><p className="font-semibold">คุณใช้สิทธิ์ไม่ครบงบประมาณ</p><p className="mt-2 text-sm leading-7">ซื้อ {money(total)} บาท จากงบ {money(student.budget)} บาท ส่วนที่เหลือ {money(remaining)} บาทจะเสียสิทธิ์ และไม่สามารถใช้ส่วนที่เหลือในภายหลังได้</p><label className="mt-4 flex cursor-pointer items-start gap-3 text-sm font-semibold leading-7"><input type="checkbox" className="mt-1 h-5 w-5 shrink-0 accent-amber-700" checked={acknowledgeUnusedBudget} disabled={busy} onChange={e => setAcknowledgeUnusedBudget(e.target.checked)} /><span>ข้าพเจ้ายืนยันว่า หากซื้อไม่ครบงบประมาณ จะเสียสิทธิ์ในส่วนที่เหลือ</span></label></div>}<div className="mt-6 flex gap-3"><button className="btn" disabled={busy || !orderingAllowed || remaining < 0 || (remaining > 0 && !acknowledgeUnusedBudget)} onClick={submit}><ActionCheckCircle2 className="mr-1.5" />{busy ? "กำลังบันทึก…" : "ยืนยันสั่งซื้อ"}</button><button className="btn-secondary" disabled={busy} onClick={() => setConfirm(false)}><ActionArrowLeft className="mr-1.5" />กลับไปแก้ไข</button></div></Modal>}
    {receipt && order && <Modal hideTitle title="ใบสั่งซื้ออุปกรณ์การเรียน" close={() => setReceipt(false)}><Receipt order={order} /></Modal>}
  </>;
}
